[project]
name = "pars-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.4.1",
    "sqlmodel>=0.0.16",
    "pydantic-settings>=2.2.1",
    "asyncpg>=0.29.0",
    "alembic>=1.13.1",
    "redis>=5.0.3",
    "python-dotenv>=1.0.1",
    "aiohttp-socks>=0.11.0",
    "httpx[socks]>=0.28.1",
    "fake-useragent>=2.2.0",
    "loguru>=0.7.3",
    "taskiq>=0.12.4",
    "taskiq-redis>=1.2.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.409",
    "ruff>=0.15.15",
]
