"""add_favorite_and_threshold_to_product

Revision ID: a252ad4f431a
Revises: 61862a2d5923
Create Date: 2026-05-30 21:07:44.713662

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a252ad4f431a"
down_revision: Union[str, Sequence[str], None] = "61862a2d5923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("is_favorite", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "product",
        sa.Column(
            "threshold",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
        ),
    )
    op.add_column(
        "product",
        sa.Column(
            "last_notified_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "last_notified_price")
    op.drop_column("product", "threshold")
    op.drop_column("product", "is_favorite")
    # ### end Alembic commands ###
